import { bool, func, node, number, object, string } from 'prop-types'

export default {
  children: node,

  accessKey: string,
  className: string,
  contentEditable: bool,
  contextMenu: string,
  dir: string,
  draggable: bool,
  hidden: bool,
  id: string,
  spellCheck: bool,
  style: object,
  tabIndex: number,
  title: string,

  onCopy: func,
  onCut: func,
  onPaste: func,
  onFocus: func,
  onBlur: func,
  onKeyDown: func,
  onKeyPress: func,
  onKeyUp: func,
  onClick: func,
  onContextMenu: func,
  onDoubleClick: func,
  onDrag: func,
  onDragEnd: func,
  onDragEnter: func,
  onDragExit: func,
  onDragLeave: func,
  onDragOver: func,
  onDragStart: func,
  onDrop: func,
  onMouseDown: func,
  onMouseEnter: func,
  onMouseLeave: func,
  onMouseMove: func,
  onMouseOut: func,
  onMouseOver: func,
  onMouseUp: func,
  onSelect: func,
  onTouchCancel: func,
  onTouchEnd: func,
  onTouchMove: func,
  onTouchStart: func,
  onScroll: func,
  onWheel: func,
  onAnimationStart: func,
  onAnimationEnd: func,
  onAnimationIteration: func,
  onTransitionEnd: func,
}
