import {MigrationInterface, QueryRunner} from "typeorm";

export class SystemTemplate1585734796486 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "plan"."plan_week_template" DROP CONSTRAINT IF EXISTS "FK_f4809f9a79100633526acd400b5"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan"."phase" DROP CONSTRAINT IF EXISTS "FK_8694f6c9d0f1a9e880fda15a785"`, undefined);
        
        await queryRunner.query(`DELETE FROM "plan"."plan_phase_template" WHERE plan_phase_template_id <= 8`);
        await queryRunner.query(`DELETE FROM "plan"."plan_phase_template" WHERE plan_phase_template_id >= 1000`);
        await queryRunner.query(`
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1, 1, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (2, 1, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (4, 1, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (5, 1, 'Grow Endurance', 'Weekly mileage is longer and workouts are more intense, to prepare you mentally and physically for the last part of your race.', 4);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (7, 1, 'Fine Tuning', 'By now you feel dialed into your training.  This is the time to practice and adjust any parts of your plan and feel confident that you''re ready to race.', 5);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (8, 1, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 6);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1000, 2, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1001, 2, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1002, 2, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1003, 2, 'Grow Endurance', 'Weekly mileage is longer and workouts are more intense, to prepare you mentally and physically for the last part of your race.', 4);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1004, 2, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 5);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1008, 3, 'Grow Endurance', 'Weekly mileage is longer and workouts are more intense, to prepare you mentally and physically for the last part of your race.', 4);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1009, 3, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 5);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1010, 4, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1011, 4, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1005, 3, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1006, 3, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1007, 3, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1012, 4, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1013, 4, 'Grow Endurance', 'Weekly mileage is longer and workouts are more intense, to prepare you mentally and physically for the last part of your race.', 4);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1014, 4, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 5);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1015, 5, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1016, 5, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1017, 5, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1018, 5, 'Grow Endurance', 'Weekly mileage is longer and workouts are more intense, to prepare you mentally and physically for the last part of your race.', 4);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1019, 5, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 5);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1020, 6, 'Build a Base', 'This phase builds on the foundation you bring to the plan and develops habits that you''ll use during training. You should feel comfortable running the first week''s long run, which will increase in mileage slowly.', 1);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1021, 6, 'Tackle Hills', 'Hill work is important, even if your race is flat. Hills improve your leg power, endurance, anaerobic capacity, speed, and cadence.', 2);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1022, 6, 'Develop Speed', 'Speed work makes you more efficient by improving your running economy (the amount of oxygen you consume) and training your muscles to handle lactic acid when you''re working hard.', 3);
INSERT INTO plan.plan_phase_template (plan_phase_template_id, plan_template_id, name, description, number_of_phase) VALUES (1023, 6, 'Taper & Race', 'Now''s the time you trust the work you have put in and mentally prepare for race day! Lower milage will allow you to prioritize sleep, hydration, nutrition, and recovery.', 4);
        `);
        await queryRunner.query(`SELECT pg_catalog.setval('plan.plan_phase_template_plan_phase_template_id_seq', 2000, true);`);

 
        await queryRunner.query(`DELETE FROM "plan"."plan_week_template" WHERE plan_week_template_id <= 91`);
        await queryRunner.query(`
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (78, 13, 'This week is high in miles and intensity, but will build critical aerobic endurance that will carry you through your race. If you feel worn down mid-week, take one of the recovery runs off. Prioritize nailing your 20 miler, this is a really important mental and physical building block of your training! If you''re struggling this week, set up a call with your Bird coach.', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (79, 14, 'Only a few more weeks until your race! Your training is peaking and you''re probably feeling it. This week is a bit of a break before one last high mileage and intensity week next week. If you''re feeling worn out or have any aches and pains, this is a great week to get a massage and some extra rest. Focus on staying healthy and preparing for your biggest week yet in week 15!', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (80, 15, 'This is the peak of your training cycle! It seems like a lot, but you''ve worked up to it and you''re prepared for a 22 miler. Since this week is intense, make sure you are eating and hydrating enough to recover in between workouts. Take the 22 miler seriously and treat it as a dry run for your race. Wear the gear you plan to race in and use the same hydration and nutrition strategy you will in the race (consuming calories every 45 minutes). Notice how marathon pace feels at the end of the run-- trust your fitness and stay mentally engaged at the end. Good luck!', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (81, 16, 'You made it to the taper! You probably already know that the taper is a magical time where your body absorbs the benefits of all of your training and it all adds up to more than you put in. You have put in all the hard training, now the way you''ll PR this year is to take the taper just as seriously. Taper like the pros do: get tons of sleep, stay off your feet and be good to yourself.  This week we''ll cut your mileage but keep the intensity of your speed and tempo workouts. Next week you''ll cut your mileage even more.  If your marathon is local, try to do your long run along the course and visualize race day.', 1019);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (82, 17, 'You are one week away from race week! Focus on resting your body this week and mentally preparing for your race. Research the race course and try to do your long run along the course if it''s local. Start planning your race weekend logistics: when will you visit the expo, how will you get to the race, will you have friends supporting you on the course? You want no surprises on race day. ', 1019);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (83, 18, 'You made it to race week! You should be proud of all the hard work you put in. Check out your progress in the app and congratulate yourself on how far you''ve come. Make sure to schedule a phone call with your Bird coach this week to talk through your race plan. Most importantly, don''t do anything new on race day. Your pace, gear, nutrition, and routines should all feel familiar by now-- trust them. Make sure you''re super clear on your pacing strategy before the race: unless your coach says differently, stick to your marathon pace for the first 20 miles. This should feel like you''re holding back a little until the last miles of the race, when you can let it rip! You''ve been practicing negative splits for weeks, you are ready!', 1019);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (32, 4, 'Ready to kick off phase two? By now you should be feeling more comfortable running 4-6 times per week. This week we''ll challenge you to grow with slightly faster mile repeats and your longest run yet. With the jump in mileage, remember to stretch before and after every run, and try to fit a yoga class in this week. Your body will thank you!', 1006);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (36, 8, 'Welcome to week 8, this is a big one! This week you''ll tackle a challenging hill workouts AND do a half marathon-- you are getting very fit. Treat this race as a dry run of your marathon: practice everything that will happen on race day, including clothes, gear, pre-race meal, when to take gels during the race, and any other rituals that work for you. Make sure you get to the race early to get your packet, use the bathroom and warm up. If you haven''t talked to your coach yet, schedule a call this week to talk through your race plan!', 1007);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (37, 9, 'This week we pull back a bit after your race. What did you learn in your race? Should your marathon pace goal be adjusted? What parts were hard that you''d like to practice? Let''s use this week to reset and focus on what you want to work on in the second half of your plan. If you''ve developed any aches and pains, start stretching and foam rolling before and after hard workouts. If you think you''re developing an injury, don''t wait to get it checked out.', 1007);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (38, 10, 'This is a BIG week, hope you''re ready! You''ll be kicking it up a notch by holding speedy paces for longer and with shorter rest breaks. You will also do your longest run yet. Hopefully you''ve been focusing on nutrition during this training plan, but as your mileage goes up in the middle weeks, it''s critical to make sure you''re getting the right pre- and post- workout meals. Try to eat a light meal before hard or long runs that includes carbs and a little protein that will stick with you but not upset your stomach (toast and peanut butter is a winner). Make sure you get some calories and protein in within 30 minutes of finishing a hard workout (chocolate milk or a protein bar are great), and a good meal within two hours. As the training gets harder in the second half of your plan, this is even more important!', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (39, 11, 'This week you''ll be doing benchmark #3 to see how far your fitness has come. You''ve put in 10 weeks of hard work, you should be proud of yourself! You''ll also be doing speed with shorter rest intervals and another long run with a fast finish -- all of which will make you fitter this week.', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (40, 12, 'This is a down week, you deserve it. You''ve probably noticed the importance of a good recovery routine by now. If your body is craving sleep, food, or a day off, listen to it. Overtraining is a real risk in your first (or first few) marathon cycles and leads to injuries and disappointing races. If you have any concerns or questions at this point in your training, schedule a call with your coach. Enjoy the rest week!', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (41, 13, 'You''re in the meat of your training cycle, where workouts are getting pretty long. This is the Growing Endurance phase, after all. As a beginner, the goal of really long runs is to get comfortable being on your feet for hours. Easy paces should feel easy, don''t make it harder on yourself. Find a way to relax as much as you can, music or conversations with buddies make the miles fly by. Pro tip for long runs: use some Body Glide to prevent chafing, no one wants that!', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (42, 14, 'Only a few more weeks until your race! Your training is peaking and you''re probably feeling it. This week is a bit of a break before one last high mileage and intensity week next week. If you''re feeling worn out or have any aches and pains, this is a great week to get a massage and some extra rest. Focus on staying healthy and preparing for your biggest week yet in week 15!', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (43, 15, 'Are you ready? This is the peak of your training! It seems like a lot, but you''ve worked up to it and believe it or not, you''re prepared for a 20 miler. Since this week is intense, make sure you are eating and hydrating enough to recover in between workouts. Take the 20 miler seriously and treat it as a dry run for your race. Wear the gear you plan to race in and use the same nutrition strategy. Notice how your body and mind feel during the run, especially the last few miles. In the race, you can remind yourself that you''ve felt this way before and you got through it.  Good luck!', 1008);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (44, 16, 'You made it to the taper! The taper is a magical time where your body absorbs the benefits of all of your training and it all adds up to more than you put in. Tapering is the reason you can go from 20 miles to 26.2 on race day.  This week we''ll cut your mileage but keep the intensity of your speed and tempo workouts. Next week you''ll cut your mileage even more. Trust your training so far and take the taper seriously! Get tons of sleep, stay off your feet and be good to yourself. If your marathon is local, try to do your long run along the course.', 1009);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (45, 17, 'You are one week away from race week! Focus on resting your body this week and mentally preparing for your race. Research the race course and try to do your long run along the course if it''s local. Start planning your race weekend logistics: when will you visit the expo, how will you get to the race, will you have friends supporting you on the course? You want no surprises on race day.', 1009);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (46, 18, 'You made it to race week! You should be proud of all the work you put in. Check out your progress in the app and congratulate yourself on how far you''ve come. Make sure to schedule a phone call with your Bird coach this week to talk through your race plan. Most importantly, don''t do anything new on race day! Your pace, gear, nutrition, and routines should all feel familiar by now-- trust them. The best thing you can do in your race is to resist the excitement and stick to your race pace, especially for the first 20 miles. You''ll feel great and like you can go faster at the beginning but don''t-- this will backfire. You should feel like you''re holding back a little until the last miles of the race.', 1009);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (20, 4, 'I feel the need...the need for speed! By now you should be feeling more comfortable running this mileage, so let''s work on holding faster paces for longer periods of time. This week we''ll challenge you to grow with half mile repeats and your longest run yet. With the jump in mileage, remember to stretch before and after every run, and try to fit a yoga class in this week. Your body will thank you!', 1001);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (21, 5, 'We''re five weeks into your marathon training, now is a good time to reflect on what''s different this cycle. Are you looking to PR? Have any old injuries resurfaced? What has changed in the rest of your life since your last good training cycle? Sometimes you can control the variables in your life to focus on training, but often you can''t. If you need help adjusting your plan to fit your life or this year''s goals, set up a phone call with your Bird coach. ', 1002);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (22, 6, 'If you didn''t know, hills pay bills on race day! Pro tip: when running a hill, keep your eyes focused on the top, lean forward from the hips (not your shoulders), and really pump your arms to generate forward momentum. Think about exploding off your back foot rather than lunging with your front foot. If you''re doing it right, your core and butt should be sore the next day too. If you live in a flat area, try to find hills in a park or on a ramp. If you need to, you can do hill workouts on a treadmill.', 1002);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (23, 7, 'You''re 7 weeks out from your race, and your training is peaking in this phase. You''ve built a TON of fitness already, now we''re solidifying your aerobic endurance and practicing skills and pacing you will use in the race. Now is a great time to address any questions that have come up with your coach, and to get any nagging aches checked out. Prioritize staying healthy in the next few weeks and taking recovery as seriously as your workouts.', 1003);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (25, 9, 'Hope you''re ready for a big week! You''ll be kicking it up a notch by holding speedy paces for longer and with shorter rest breaks. You''ll also be doing your longest run yet. Hopefully you''ve been focusing on nutrition during this training plan, but as your mileage goes up, it''s critical to make sure you''re getting the right mix of carbs and protein in pre- and post- workout meals. Make sure you get some calories and protein in within 30 minutes of finishing a hard workout (chocolate milk or a protein bar are great), and a good meal within two hours. ', 1003);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (26, 10, 'You made it to the taper! You probably already know that the taper is a magical time where your body absorbs the benefits of all of your training and it all adds up to more than you put in. You have put in all the hard training, now the way you''ll PR this year is to take the taper just as seriously. Taper like the pros do: get tons of sleep, stay off your feet and be good to yourself.  This week we''ll cut your mileage but keep the intensity of your speed and tempo workouts. Next week you''ll cut your mileage even more.  If your race is local, try to do your long run along the course and visualize race day.', 1004);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (27, 11, 'You are one week away from race week! Focus on resting your body this week and mentally preparing for your race. Research the race course and try to do your long run along the course if it''s local. Start planning your race weekend logistics: when will you visit the expo, how will you get to the race, will you have friends supporting you on the course? You want no surprises on race day. ', 1004);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (28, 12, 'You made it to race week! You should be proud of all the hard work you put in. Check out your progress in the app and congratulate yourself on how far you''ve come. Make sure to schedule a phone call with your Bird coach this week to talk through your race plan. Most importantly, don''t do anything new on race day. Your pace, gear, nutrition, and routines should all feel familiar by now-- trust them. Make sure you''re super clear on your pacing strategy before the race: unless your coach says differently, stick to your race pace for the first 8-10 miles, then shave off 10 seconds per mile until you are at tempo effort. You''ve been practicing negative splits for weeks, you are ready!', 1004);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (52, 6, 'Wow, you''re already six weeks into your marathon plan. What have you learned so far? What''s different from your last training cycle? Now''s a good time to consider your gear. You have three more months of training, you might want to invest in some high quality running clothes that are comfortable and keep you dry, and a waterproof layer so that there''s no excuse to miss your workout on rainy days. Have you been wearing your running shoes for months? This is the right time to buy ones you can wear in your race. ', 1011);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (53, 7, 'To run a better marathon this year, don''t just get in the miles, you''ll need to focus on strength and power. Hills are one of the best ways to develop running efficiency that will allow you to sustain your goal pace when you''re tired. Pro tip: when running a hill, keep your eyes focused on the top, lean forward from the hips (not your shoulders), and really pump your arms to generate forward momentum. Think about exploding off your back foot rather than lunging with your front foot. If you''re doing it right, your core and butt should be sore the next day too. Note: even if you live in a flat area, try to find hills in a park or on a ramp. If you need to, you can do hill workouts on a treadmill.							', 1012);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (54, 8, 'This is a big week of challenging hill repeats and a solid long run. The hills will still be hard, but should feel more familiar after last week. Don''t forget to lean forward from the hips, keep your eyes on the top of the hill, and pump your arms to power you up. Also make sure you register for a half marathon next weekend!', 1012);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (55, 9, 'It''s race week! Treat this race as a dry run of your marathon: practice everything that will happen on race day, including clothes, gear, pre-race meal, when to take gels during the race, and any other rituals that work for you. Make sure you get to the race early to get your packet, use the bathroom and warm up. If you haven''t talked to your coach yet, schedule a call this week to talk through your race plan.', 1012);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (56, 10, 'This is a big week, hope you''re ready! You''ll be kicking it up a notch by holding speedy paces for longer and with shorter rest breaks. You will also do your longest run yet. Hopefully you''ve been focusing on nutrition during this training plan, but as your mileage goes up in the middle weeks, it''s critical to make sure you''re getting the right pre- and post- workout meals. Try to eat a light meal before hard or long runs that includes carbs and a little protein that will stick with you but not upset your stomach (toast and peanut butter is a winner). Make sure you get some calories and protein in within 30 minutes of finishing a hard workout (chocolate milk or a protein bar are great), and a good meal within two hours. As the training gets harder in the second half of your plan, this is even more important!						', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (57, 11, 'This week you''ll be doing benchmark #3 to see how far your fitness has come. You''ve put in 10 weeks of hard work, you should be proud of yourself! You''ll also be doing speed with shorter rest intervals and another long run with a fast finish -- all of which will make you fitter this week. This is a great time to check in with your Bird coach, review your progress and adjust your plan if necessary.', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (58, 12, 'This is a down week, you deserve it. The difference between a good week of training and a great week of training has a lot to do with how well you recover between workouts. If your body is craving sleep, food, or a day off, listen to it. Overtraining is a real risk in marathon training and leads to injuries and disappointing races. If you have any concerns or questions at this point in your training, schedule a call with your coach. Enjoy the rest week!', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (59, 13, 'This week is high in miles and intensity, but will build critical aerobic endurance that will carry you through your race. If you feel worn down mid-week, take one of the recovery runs off. Prioritize nailing your 20 miler, this is a really important mental and physical building block of your training! If you''re struggling this week, set up a call with your Bird coach.', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (61, 15, 'Are you ready? This is the peak of your training! It seems like a lot, but you''ve worked up to it and believe it or not, you''re prepared for a 22 miler. Since this week is intense, make sure you are eating and hydrating enough to recover in between workouts. Take the 22 miler seriously and treat it as a dry run for your race. Wear the gear you plan to race in and use the same nutrition strategy (consuming calories every 45 minutes). Notice how your body and mind feel during the run, especially the last few miles. In the race, you can remind yourself that you''ve felt this way before and you got through it.  Good luck!', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (62, 16, 'You made it to the taper! The taper is a magical time where your body absorbs the benefits of all of your training and it all adds up to more than you put in. Tapering is the reason you can go from 22 miles to 26.2 on race day.  This week we''ll cut your mileage but keep the intensity of your speed and tempo workouts. Next week you''ll cut your mileage even more. The way you''ll PR this year is to take the taper as seriously as you do training. Get tons of sleep, stay off your feet and be good to yourself. If your marathon is local, try to do your long run along the course.', 1014);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (63, 17, 'You are one week away from race week! Focus on resting your body this week and mentally preparing for your race. Research the race course and try to do your long run along the course if it''s local. Start planning your race weekend logistics: when will you visit the expo, how will you get to the race, will you have friends supporting you on the course? You want no surprises on race day. ', 1014);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (64, 18, 'You made it to race week! Are you excited? You should be proud of all the work you put in. Check out your progress in the app and congratulate yourself on how far you''ve come. Make sure to schedule a phone call with your Bird coach this week to talk through your race plan. Most importantly, don''t do anything new on race day! Your pace, gear, nutrition, and routines should all feel familiar by now-- trust them. The best thing you can do in your race is to resist the urge to go faster than your pacing strategy. Unless your coach says differently, stick to your marathon pace for the first 20 miles. You should feel like you''re holding back a little until the last miles of the race, when you can let it rip! You are ready!', 1014);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (70, 5, 'Are you ready for speed? This week we''ll be increasing your tempo distance and incorporating 800 meter intervals. As your training gets more intense, you''re going to have to adjust your lifestyle to fuel your growth and level up this season. You should be drinking enough water before, during, and after workouts to replace the fluids you lose through sweat. You also need to eat enough good carbs (not junk food) to power your hard workouts. To train at an advanced level, you have to take good care of yourself in between workouts.', 1016);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (73, 8, 'This is a big week of challenging hill repeats and a solid long run. The hills should feel more familiar after last week. Don''t forget to lean forward from the hips, keep your eyes on the top of the hill, and pump your arms to generate momentum. Also make sure you register for a half marathon next weekend!', 1017);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (84, 1, 'Welcome to the first week of your training plan! Give yourself a pat on the back for setting a goal and starting to work towards it.  In the next eight weeks we will focus on building your aerobic base so you feel comfortable running a 10k distance, getting familiar with different effort levels and paces, and working on strength and flexibility to prevent injuries. You can expect to do 4-5 workouts a week, including 3-4 runs. Make sure to answer the texts you get from Bird to log your progress, and don''t forget that you can schedule two phone calls with your coach if you''ve got questions at any time. Let''s go!', 1020);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (85, 2, 'Congrats! You made it through your first week. If any of the workouts felt unsustainable, adjust your pacing this week. Recovery and long runs should feel like you could sustain the pace for a long time, even if that means slowing down your pace. Tempo and speed paces are working hard, but should not be an all out sprint. If you''re unable to complete the whole workout, you''re working too hard.	Why do we do tempo and speed runs in a beginner plan? They teach your muscles to sustain hard work when they''re tired, which is super useful in a race. We''ll use faster and more intense workouts to build muscle and balance the longer, slower runs that build endurance.', 1020);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (86, 3, 'You''re building your aerobic base even more this week with a longer tempo and 5 mile long run. Focus on settling into the right pace for both of these workouts, finding a smooth rhythm, and relaxing as much as you can. Good form also helps you not waste energy-- relax your shoulders and feel your thumbs brush your hips with each stride instead of holding your arms high and tight. Keeping an open chest instead of hunching your shoulders will help you breathe more efficiently, too.', 1020);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (87, 4, 'Congratulations, you''ve built a lot of fitness in the last three weeks, now you''re ready to start incorporating hills. Why do you need to do hills if your race is flat? Hills are a secret ingredient of many endurance training plans because they build power, improve your form, and create an anaerobic spike in your heart rate that pushes your fitness higher than almost any other workout. Plus, it''s more fun to mix things up, right?', 1021);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (89, 6, 'You''re three quarters of the way through your training plan, how do you feel? Hopefully you''ve noticed that you''re able to run farther, faster, and more often than you could a few weeks ago. That was no accident, you put the work in. This is the last week of hard training before we start to decrease mileage in the taper. Make it a good week!', 1022);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (90, 7, 'You''re still in the speed phase, but we''ll be starting to taper this week by cutting your mileage while maintaining the intensity of your key workouts. Do your best to do all of them as written, it''s the last week to gain fitness before you focus on resting and absorbing the benefits of your training cycle. There''s plenty of recovery time this week, get the most out of it by stretching, getting a lot of rest, and hydrating between workouts.', 1022);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (18, 2, 'Congrats on finishing your first week of training! You now have your first benchmark time, which is a measure of your fitness at the beginning of this plan. Each week we will build on your tempo, speed, and long workouts, and measure your progress again in a few weeks. This week you''ll practice your tempo pace again--this should feel uncomfortably hard but not a sprint. We''re training your muscles to work efficiently when they are producing lactic acid (that burning feeling). Stick with the tempo workouts and you''ll see your fitness steadily grow.', 1000);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (17, 1, 'Welcome to the first week of your half marathon training plan! You''re training at an advanced level, so the focus of the next 14 weeks is to build on your aerobic base and ability to sustain hard work. Week one is all about getting into the rhythm of a typical training week and setting a baseline for your fitness that we''ll build on. Don''t forget to answer the texts you get from Bird to log your workouts.', 1000);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (19, 3, 'This week we''re starting to focus on speed with longer tempo and speed workouts. Notice how you feel doing them compared to last week. Don''t forget, you can have two free phone calls with a Bird coach at any point in your training plan. If you run into questions or concerns, please reach out!', 1001);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (29, 1, 'Welcome to the first week of your marathon training plan! This week you''re probably feeling a surge of motivation, some jitters, and wondering how the next 18 weeks are going to go. Not to worry, week one is all about getting into the rhythm of a typical training week and setting a baseline for your fitness that we''ll build on. Don''t forget to answer the texts you get from Bird, and record your benchmark times!', 1005);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (30, 2, 'Congrats on finishing your first week of training! You now have your first benchmark time, which is a measure of your fitness at the beginning of this plan. Each week we will build on your tempo, speed, and long workouts, and measure your progress again in a few weeks. This week you''ll up your tempo to two miles-- this pace should feel uncomfortably hard but not a sprint. It''s challenging, but so important! We''re training your muscles to work efficiently when they are producing lactic acid (that burning feeling). Stick with the tempo workouts and you''ll see your fitness steadily grow.', 1005);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (31, 3, 'Congrats! We''re wrapping up the first phase of your training plan. How are you feeling? You''ve already done one of each of workout, and probably learned which ones are the toughest.  This week we''ll continue building an aerobic base with some easy, bread and butter runs. We''ll also start training your body and mind to get used to your race pace, so eventually you can run it on autopilot.', 1005);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (3, 3, 'This week we''ll continue building an aerobic base with a longer long run and longer speed workouts. Notice how you feel doing them compared to last week. Don''t forget, you can have two free phone calls with a Bird coach at any point in your training plan. If you run into questions or concerns, please reach out!', 1);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (10, 10, 'This is a down week, you deserve it. You''ve probably noticed the importance of a good recovery routine by now. If your body is craving sleep, food, or a day off, listen to it. Overtraining is a real risk in your first (or first few) training cycles and leads to injuries and disappointing races. If you have any concerns or questions at this point in your training, schedule a call with your coach. Enjoy the rest week!', 4);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (47, 1, 'Welcome to the first week of your marathon training plan! You are training at an intermediate level, so we''ll be building on the basics to sustain your pace goals and get comfortable with higher mileage. Not to worry, week one is all about getting into the rhythm of a typical training week and setting a baseline for your fitness. Don''t forget to answer the texts you get from Bird, and record your benchmark time!', 1010);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (50, 4, 'Ready to kick off phase two? By now you should be feeling comfortable running 4-6 times per week. This week we''ll challenge you to grow with slightly faster mile repeats and a longer long run. With the jump in mileage, remember to stretch before and after every run, and try to fit a yoga class in this week. Your body will thank you!', 1011);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (60, 14, 'Only a few more weeks until your race! Your training is peaking and you''re probably feeling it. This week is a bit of a break before one last high mileage and intensity week next week. If you''re feeling worn out or have any aches and pains, this is a great week to get a massage and some extra rest. Focus on staying healthy and preparing for your biggest week yet in week 15!', 1013);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (66, 1, 'Welcome to the first week of your marathon training plan! You are training at an advanced level, so we''ll be training at higher mileage, drilling into pacing and focusing on sustaining hard work. Let''s use this week to get into the rhythm of a typical training week and set a baseline for your fitness. Don''t forget to answer the texts you get from Bird and record your benchmark times!', 1015);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (67, 2, 'Congrats on nailing your first week of training! You now have your first benchmark time, which is a measure of your fitness at the beginning of this plan. Each week we will build on your tempo, speed, and long workouts, and measure your progress again in a few weeks. we''re working the tempo pace-- this pace should feel uncomfortably hard but not a sprint. We''re training your muscles to work efficiently when they are producing lactic acid so you can sustain higher paces when you''re tired in the race.', 1015);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (68, 3, 'Congrats! We''re wrapping up the first phase of your training plan. It might have felt a litte easy, but we''re building skills that will help you PR this season. This week we''ll continue building an aerobic base with some bread and butter runs. We''ll also start working your goal race pace, so eventually you can run it on autopilot. This is a down week before high intensity in week 4. ', 1015);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (69, 4, 'Ready to kick it up a notch? By now you should be feeling comfortable running 4-6 times per week. This week we''ll challenge you with faster mile repeats and a longer long run. With the jump in mileage, remember to prioritize stretching and foam rolling, and try to fit a yoga class in this week. And don''t forget to answer the daily texts from Bird, this is how we collect data to adjust your plan as you progress.', 1016);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (1, 1, 'Welcome to the first week of your half marathon training plan! This week you''re probably feeling a surge of motivation, some jitters, and wondering how the next 14 weeks are going to go. Not to worry, week one is all about getting into the rhythm of a typical training week and setting a baseline for your fitness that we''ll build on. Don''t forget to answer the texts you get from Bird, and record your benchmark times!', 1);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (2, 2, 'Congrats on finishing your first week of training! You now have your first benchmark time, which is a measure of your fitness at the beginning of this plan. Each week we will build on your tempo, speed, and long workouts, and measure your progress again in a few weeks. This week you''ll up your tempo to 1.5 miles-- this pace should feel uncomfortably hard but not a sprint. It''s challenging, but so important! We''re training your muscles to work efficiently when they are producing lactic acid (that burning feeling). Stick with the tempo workouts and you''ll see your fitness steadily grow.', 1);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (4, 4, 'Congrats! We''re wrapping up the first phase of your training plan. How are you feeling? You''ve already done one of each of workout, and probably learned which ones are the toughest.  This week we''ll continue building an aerobic base with some easy, bread and butter runs. We''ll also start training your body and mind to get used to your race pace, so eventually you can run it on autopilot.', 1);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (5, 5, 'I feel the need...the need for speed! Welcome to phase two. By now you should be feeling more comfortable running 4-5 times a week, so let''s work on holding faster paces for longer periods of time. This week we''ll challenge you to grow with mile repeats and your longest run yet. With the jump in mileage, remember to stretch before and after every run, and try to fit a yoga class in this week. Your body will thank you!', 2);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (6, 6, 'Wow, you''re six weeks into your half marathon plan. You should be proud of yourself! Now''s a good time to consider your gear. You have two more months of training, you might want to invest in some high quality running clothes that are comfortable and keep you dry, and a waterproof layer so that there''s no excuse to miss your workout on rainy days. This is also the right time to buy shoes you can wear in your race. And finally, the secret weapon of veteran runners is... a hat! A hat that keeps the sun out of your eyes is really helpful on long runs to keep you cool and prevent hours of squinting. Really!', 2);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (7, 7, 'If you didn''t know, hills pay bills on race day! Yes, they are hard, but they make you stronger, too. Pro tip: when running a hill, keep your eyes focused on the top, lean forward from the hips (not your shoulders), and really pump your arms to generate forward momentum. Think about exploding off your back foot rather than lunging with your front foot. If you''re doing it right, your core and butt should be sore the next day too. If you live in a flat area, try to find hills in a park or on a ramp. If you need to, you can do hill workouts on a treadmill.', 3);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (8, 8, 'Welcome to a big week! You''ll be building on your hill work from last week, and doing your longest run yet. You are getting VERY fit. If you haven''t talked to your Bird coach yet, now is a great time to schedule a call to discuss your progress and modify your plan if necessary.', 3);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (9, 9, 'You''re 5 weeks out from your race, and your training is peaking. You''ve built a TON of fitness already, now we''re solidifying your aerobic endurance and practicing skills and pacing you will use in the race. Now is a great time to address any questions that have come up with your coach, and to get any nagging aches checked out. Prioritize staying healthy in the next few weeks and taking recovery as seriously as your workouts.', 4);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (88, 5, 'Week 5 is a great time to check in with your coach about how you''re doing with the workouts, ask about any aches or pains that you''re having, and adjust the rest of your plan if necessary. You''ve got two more weeks of solid work before you start tapering for your race. This is a big week to make some gains in your fitness!', 1021);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (11, 11, 'You''re in the meat of your training cycle, where workouts are getting pretty long. This is the Growing Endurance phase, after all. As a beginner, the goal of really long runs is to get comfortable being on your feet for hours. Easy paces should feel easy, don''t make it harder on yourself. Find a way to relax as much as you can, music or conversations with buddies make the miles fly by. Pro tip for long runs: use some Body Glide to prevent chafing, no one wants that!', 4);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (12, 12, 'You made it to the taper! The taper is a magical time where your body absorbs the benefits of all of your training and it all adds up to more than you put in. This week we''ll start cutting your mileage but keep the intensity of your speed and tempo workouts. Next week you''ll cut your mileage even more. Trust your training so far and take the taper seriously! Get tons of sleep, stay off your feet and be good to yourself. If your marathon is local, try to do your long run along the course.                                                                ', 5);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (13, 13, 'You are one week away from race week! Focus on resting your body this week and mentally preparing for your race. Research the race course and try to do your long run along the course if it''s local. Start planning your race weekend logistics: when will you visit the expo, how will you get to the race, will you have friends supporting you on the course? You want no surprises on race day.', 5);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (14, 14, 'You made it to race week! You should be proud of all the work you put in. Check out your progress in the app and congratulate yourself on how far you''ve come. Make sure to schedule a phone call with your Bird coach this week to talk through your race plan. Most importantly, don''t do anything new on race day! Your pace, gear, nutrition, and routines should all feel familiar by now-- trust them. The best thing you can do in your race is to resist the excitement and stick to your race pace, especially for the first 9-10 miles. You''ll feel great and like you can go faster at the beginning but don''t-- this will backfire. You should feel like you''re holding back until the last miles of the race.', 5);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (33, 5, 'This is the develop speed phase, and you''ll get why soon. We''ll be working on your tempo pace again, and incorporating 800 meter intervals, your first anaerobic workout. You may notice some changes five weeks into training -- sore muscles, sleepiness, being hungrier. You''re going to have to adjust your lifestyle to keep up training and fuel your growth. You should be drinking water before, during, and after workouts to replace the fluids you lose through sweat. You also need to eat enough good carbs (not junk food) to have energy for your hard workouts! Doing both will make you feel better during workouts and recover faster.', 1006);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (34, 6, 'Wow, you''re six weeks into your marathon plan. You should be proud of yourself! What have you learned so far? Now''s a good time to consider your gear. You have three more months of training, you might want to invest in some high quality running clothes that are comfortable and keep you dry, and a waterproof layer so that there''s no excuse to miss your workout on rainy days. Have you been wearing your running shoes for months? This is the right time to buy ones you can wear in your race. And finally, the secret weapon of veteran marathoners is... a hat! A hat that keeps the sun out of your eyes is really helpful on long runs to keep you cool and prevent hours of squinting. Really!', 1006);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (35, 7, 'If you didn''t know, HILLS pay BILLS come race day! Yes, they are hard and they make your legs sore, but they are making you stronger, too. Pro tip: when running a hill, keep your eyes focused on the top, lean forward from the hips (not your shoulders), and really pump your arms to generate forward momentum. Think about exploding off your back foot rather than lunging with your front foot. If you''re doing it right, your core and butt should be sore the next day too. If you live in a flat area, try to find hills in a park or on a ramp. If you need to, you can do hill workouts on a treadmill. Note: don''t forget to register for a half marathon next weekend!', 1007);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (24, 8, 'This is a down week, you deserve it. You''ve probably noticed the importance of a good recovery routine by now. If your body is craving sleep, food, or a day off, listen to it. If you have any concerns or questions at this point in your training, schedule a call with your coach. Enjoy the rest week!', 1003);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (48, 2, 'Congrats on finishing your first week of training! You now have your first benchmark time, which is a measure of your fitness at the beginning of this plan. Each week we will build on your tempo, speed, and long workouts, and measure your progress again in a few weeks. This week you''ll up your tempo to two miles-- this pace should feel uncomfortably hard but not a sprint. It''s challenging, but so important! We''re training your muscles to work efficiently when they are producing lactic acid (that burning feeling). Stick with the tempo workouts and you''ll see your fitness steadily grow.', 1010);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (49, 3, 'Congrats! We''re wrapping up the first phase of your training plan. How are you feeling? It might have felt a litte easy, but we''re building skills that will help you PR this season. This week we''ll continue building an aerobic base with some easy, bread and butter runs. We''ll also start training your body and mind to get used to your goal race pace, so eventually you can run it on autopilot.', 1010);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (51, 5, 'Welcome to phase two! This week we''ll be working on your tempo pace and incorporating 800 meter intervals, your first anaerobic workout. You may notice some changes five weeks into training -- sore muscles, sleepiness, being hungrier. You''re going to have to adjust your lifestyle to fuel your growth and level up this season. You should be drinking water before, during, and after workouts to replace the fluids you lose through sweat. You also need to eat enough good carbs (not junk food) to have energy for your hard workouts. Fine tuning your nutrition and hydration will you feel better during workouts and recover faster.', 1011);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (71, 6, 'We''re six weeks into your marathon training, now is a good time to reflect on what''s different this cycle. Are you looking to PR? Have any old injuries resurfaced? What has changed in the rest of your life since your last good training cycle? Sometimes you can control the variables in your life to focus on training, but often you can''t. If you need help adjusting your plan to fit your life or this year''s goals, set up a phone call with your Bird coach. ', 1016);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (72, 7, 'To run a better marathon this year, don''t just get in the miles, you''ll need to focus on strength and power. Hills are one of the best ways to develop running efficiency that will allow you to sustain your goal pace when you''re tired. Pro tip: when running a hill, keep your eyes focused on the top, lean forward from the hips (not your shoulders), and really pump your arms to generate forward momentum. Think about exploding off your back foot rather than lunging with your front foot. If you''re doing it right, your core and butt should be sore the next day too. Note: even if you live in a flat area, try to find hills in a park or on a ramp. If you need to, you can do hill workouts on a treadmill.							', 1017);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (74, 9, 'It''s race week! Treat this race as a dry run of your marathon: practice everything that will happen on race day, including clothes, gear, pre-race meal, when to take gels during the race, and any other rituals that work for you. Make sure you get to the race early to get your packet, use the bathroom and warm up. If you haven''t talked to your coach yet, schedule a call this week to talk through your race plan.', 1017);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (75, 10, 'Hope you''re ready for a big week! You''ll be kicking it up a notch by holding speedy paces for longer and with shorter rest breaks. You''ll also be doing your longest run yet. Hopefully you''ve been focusing on nutrition during this training plan, but as your mileage goes up in the middle weeks, it''s critical to make sure you''re getting the right mix of carbs and protein in pre- and post- workout meals. Make sure you get some calories and protein in within 30 minutes of finishing a hard workout (chocolate milk or a protein bar are great), and a good meal within two hours. ', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (76, 11, 'This week you''ll be doing benchmark #3 to see how far your fitness has come. You''ve put in 10 weeks of hard work, you should be proud of yourself! You''ll also be doing speed with shorter rest intervals and another long run with a fast finish -- all of which will make you fitter this week. This is a great time to check in with your Bird coach, review your progress and adjust your plan if necessary.', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (77, 12, 'This is a down week, you deserve it. The difference between a good week of training and a great week of training has a lot to do with how well you recover between workouts. If your body is craving sleep, food, or a day off, listen to it. Overtraining is a real risk, If you have any concerns or questions at this point in your training, schedule a call with your coach. And if any aches and pains are persistent, now is the time to get them checked out. Enjoy the rest week!', 1018);
INSERT INTO plan.plan_week_template (plan_week_template_id, number_of_week, description, plan_phase_template_id) VALUES (91, 8, 'The taper is a magical period of your training where everything comes together and adds up to more than the sum of what you put in. Believe it or not, by intentionally resting and cutting back before the race, your body absorbs the benefits of your training and will be able to go farter and faster than you could last week. Your job this week is to focus on taking good care of yourself-- lots of sleep, lots of healthy food, and no extra stress on your body. Make sure you talk to your coach this week to go over your race plan. Well done in the last eight weeks, have a GREAT race!', 1023);
        `);

        await queryRunner.query(`SELECT pg_catalog.setval('plan.plan_week_template_plan_week_template_id_seq', 500, true);`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
    }

}
